import type { Metadata } from "next"
import { ReactNode } from "react"
import "./globals.css"

export const metadata: Metadata = {
  title: "Saint Vinci",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode
}>) => {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  )
}
export default RootLayout
