import { ReactNode } from "react"
import "./globals.css"
import updateTitle from "@/utils/updateTitle"
import Header from "@/components/Header"
import Footer from "@/components/Footer"

export const metadata = updateTitle({
  description: "Generated by create next app",
})

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode
}>) => {
  return (
    <html lang="fr">
      <body>
        <main className="flex flex-col min-h-screen">
          <Header></Header>
          <section className="flex flex-col flex-grow">{children}</section>
          <Footer></Footer>
        </main>
      </body>
    </html>
  )
}
export default RootLayout
